[package]
name = "slack-service"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-runtime = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
