name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Variables
      run: |
        echo "BUCKET_NAME=com.cuffney.slack-service" >> $GITHUB_ENV
  
    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose
