name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Variables
      run: |
        echo "BUCKET_NAME=com.cuffney.slack-service" >> $GITHUB_ENV
  
    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Create S3 bucket
      run: |
        if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME already exists. Skipping creation."
        else
            echo "Creating bucket $BUCKET_NAME..."
            aws s3 mb "s3://$BUCKET_NAME"
        fi

